import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { QueryProvider } from "@/providers/query-provider";
const inter = Inter({ subsets: ["latin"] });
import { SheetProvider } from "@/providers/sheet-provider";
import { Toaster, toast } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            <SheetProvider />
            <Toaster />
             {children}
             
          </QueryProvider>
          
          </body>
      </html>
    </ClerkProvider>
    
  );
}
